import '../../models/listing.dart';

const liveNowListings = [
  Listing(
    id: "sandy-toes-beach-bar",
    title: "Sandy Toes Beach Bar",
    subtitle: "Live reggae by the water",
    category: "🎵 Live Music",
    subcategory: "Beach Bar",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    gallery: [],
    rating: 4.7,
    reviewCount: 126,
    price: r"$$",
    status: "LIVE NOW",
    description:
        "A relaxed beachfront spot with music, drinks, and island energy.",
    whyYoullLoveIt:
        "Perfect for catching live music with ocean views and a casual island vibe.",
    perfectFor: ["Friends", "Live Music", "Beach Vibes"],
    features: ["Outdoor Seating", "Live Music", "Ocean View"],
    pulse: "Band playing now",
  ),
  Listing(
    id: "sunset-cruise",
    title: "Sunset Cruise",
    subtitle: "Boarding soon",
    category: "🚤 Tour",
    subcategory: "Boat Tour",
    destination: "Bahamas",
    location: "Paradise Island",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    gallery: [],
    rating: 4.8,
    reviewCount: 94,
    price: r"$$$",
    status: "STARTS SOON",
    description:
        "A scenic evening cruise with ocean views, music, and sunset photo moments.",
    whyYoullLoveIt:
        "A beautiful way to end the day on the water with friends or family.",
    perfectFor: ["Couples", "Friends", "Sunset"],
    features: ["Ocean View", "Photo Friendly", "Guided Experience"],
    pulse: "Leaves in 45 mins",
  ),
  Listing(
    id: "arawak-cay-fish-fry",
    title: "Arawak Cay Fish Fry",
    subtitle: "Local food and drinks",
    category: "🍽 Dining",
    subcategory: "Bahamian Cuisine",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    gallery: [],
    rating: 4.6,
    reviewCount: 211,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A lively local dining area known for Bahamian food, drinks, and casual nightlife.",
    whyYoullLoveIt:
        "Great for trying authentic local flavors in a fun, energetic setting.",
    perfectFor: ["Local Food", "Friends", "Casual Night"],
    features: ["Local Favorite", "Outdoor Seating", "Casual"],
    pulse: "Happy hour tonight",
  ),
];
