import '../../models/listing.dart';

const liveNowListings = [
  Listing(
    id: "sandy-toes-beach-bar",
    title: "Sandy Toes Beach Bar",
    subtitle: "Live reggae by the water",
    category: "🎵 Live Music",
    subcategory: "Beach Bar",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    gallery: [],
    rating: 4.7,
    reviewCount: 126,
    price: r"$$",
    status: "LIVE NOW",
    description:
        "A relaxed beachfront spot with music, drinks, and island energy.",
    whyYoullLoveIt:
        "Perfect for catching live music with ocean views and a casual island vibe.",
    perfectFor: ["Friends", "Live Music", "Beach Vibes"],
    features: ["Outdoor Seating", "Live Music", "Ocean View"],
    pulse: "Band playing now",
  ),
  Listing(
    id: "sunset-cruise",
    title: "Sunset Cruise",
    subtitle: "Boarding soon",
    category: "🚤 Tour",
    subcategory: "Boat Tour",
    destination: "Bahamas",
    location: "Paradise Island",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    gallery: [],
    rating: 4.8,
    reviewCount: 94,
    price: r"$$$",
    status: "STARTS SOON",
    description:
        "A scenic evening cruise with ocean views, music, and sunset photo moments.",
    whyYoullLoveIt:
        "A beautiful way to end the day on the water with friends or family.",
    perfectFor: ["Couples", "Friends", "Sunset"],
    features: ["Ocean View", "Photo Friendly", "Guided Experience"],
    pulse: "Leaves in 45 mins",
  ),
  Listing(
    id: "arawak-cay-fish-fry",
    title: "Arawak Cay Fish Fry",
    subtitle: "Local food and drinks",
    category: "🍽 Dining",
    subcategory: "Bahamian Cuisine",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    gallery: [],
    rating: 4.6,
    reviewCount: 211,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A lively local dining area known for Bahamian food, drinks, and casual nightlife.",
    whyYoullLoveIt:
        "Great for trying authentic local flavors in a fun, energetic setting.",
    perfectFor: ["Local Food", "Friends", "Casual Night"],
    features: ["Local Favorite", "Outdoor Seating", "Casual"],
    pulse: "Happy hour tonight",
  ),
  Listing(
    id: "baha-mar-resort",
    title: "Baha Mar",
    subtitle: "Dining, nightlife, and resort experiences",
    category: "✨ Resort",
    subcategory: "Resort District",
    destination: "Bahamas",
    location: "Cable Beach",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    gallery: [],
    rating: 4.7,
    reviewCount: 482,
    price: r"$$$$",
    status: "OPEN NOW",
    description:
        "A large oceanfront resort district featuring restaurants, entertainment, shopping, pools, and nightlife.",
    whyYoullLoveIt:
        "You can enjoy several different experiences in one area without travelling far.",
    perfectFor: ["Couples", "Families", "Nightlife"],
    features: ["Ocean View", "Shopping", "Restaurants", "Nightlife"],
    pulse: "Live entertainment tonight",
  ),
  Listing(
    id: "cable-beach",
    title: "Cable Beach",
    subtitle: "Soft sand and calm turquoise water",
    category: "🏖 Beach",
    subcategory: "Public Beach",
    destination: "Bahamas",
    location: "Cable Beach",
    imageUrl: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57",
    gallery: [],
    rating: 4.8,
    reviewCount: 348,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A long stretch of soft sand and clear water near Nassau's resort district.",
    whyYoullLoveIt:
        "It is easy to reach, beautiful, and works equally well for swimming or relaxing.",
    perfectFor: ["Couples", "Families", "Beach Vibes", "Sunset"],
    features: ["Ocean View", "Family Friendly", "Photo Friendly"],
    pulse: null,
  ),

  Listing(
    id: "junkanoo-beach",
    title: "Junkanoo Beach",
    subtitle: "A lively beach close to downtown",
    category: "🏖 Beach",
    subcategory: "Public Beach",
    destination: "Bahamas",
    location: "Downtown Nassau",
    imageUrl: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda",
    gallery: [],
    rating: 4.5,
    reviewCount: 294,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A convenient beach near downtown Nassau with food, music, and a social atmosphere.",
    whyYoullLoveIt:
        "It is easy to combine with downtown sightseeing, shopping, and local food.",
    perfectFor: ["Friends", "Families", "Casual Day"],
    features: ["Local Favorite", "Food Nearby", "Ocean View"],
    pulse: "Beach bars are getting busy",
  ),

  Listing(
    id: "love-beach",
    title: "Love Beach",
    subtitle: "A quieter escape west of Nassau",
    category: "🏖 Beach",
    subcategory: "Quiet Beach",
    destination: "Bahamas",
    location: "West Nassau",
    imageUrl: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    gallery: [],
    rating: 4.8,
    reviewCount: 117,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A peaceful beach known for clear water, fewer crowds, and relaxed scenery.",
    whyYoullLoveIt:
        "It feels removed from the busiest tourist areas while still being accessible from Nassau.",
    perfectFor: ["Couples", "Relaxing", "Sunset"],
    features: ["Hidden Gem", "Ocean View", "Quiet"],
    pulse: null,
  ),

  Listing(
    id: "cafe-matisse",
    title: "Café Matisse",
    subtitle: "Italian dining in a charming courtyard",
    category: "🍽 Dining",
    subcategory: "Italian Restaurant",
    destination: "Bahamas",
    location: "Downtown Nassau",
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
    gallery: [],
    rating: 4.8,
    reviewCount: 328,
    price: r"$$$",
    status: "OPEN TONIGHT",
    description:
        "An intimate restaurant serving Italian-inspired dishes in a colourful historic setting.",
    whyYoullLoveIt:
        "The courtyard atmosphere makes it especially memorable for a relaxed evening meal.",
    perfectFor: ["Couples", "Date Night", "Dinner"],
    features: ["Outdoor Seating", "Romantic", "Local Favorite"],
    pulse: "Limited dinner tables remain",
  ),

  Listing(
    id: "dune-restaurant",
    title: "Dune",
    subtitle: "Oceanfront dining with sunset views",
    category: "🍽 Dining",
    subcategory: "Fine Dining",
    destination: "Bahamas",
    location: "Paradise Island",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    gallery: [],
    rating: 4.7,
    reviewCount: 412,
    price: r"$$$$",
    status: "OPEN TONIGHT",
    description:
        "An elegant oceanfront restaurant offering international dishes with Bahamian influences.",
    whyYoullLoveIt:
        "The combination of ocean views, polished service, and sunset dining makes it ideal for special occasions.",
    perfectFor: ["Couples", "Date Night", "Sunset"],
    features: ["Ocean View", "Romantic", "Fine Dining"],
    pulse: "Sunset tables filling quickly",
  ),

  Listing(
    id: "cafe-channing-noelle",
    title: "Café Channing Noelle",
    subtitle: "Coffee, pastries, and an easy morning",
    category: "☕ Coffee",
    subcategory: "Café",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb",
    gallery: [],
    rating: 4.6,
    reviewCount: 86,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A welcoming café serving coffee, pastries, breakfast, and light meals.",
    whyYoullLoveIt:
        "It is a comfortable place to begin the day or take a break between activities.",
    perfectFor: ["Breakfast", "Coffee", "Casual"],
    features: ["Local Favorite", "Breakfast", "Quick Stop"],
    pulse: "Fresh pastries available",
  ),

  Listing(
    id: "blue-lagoon-island",
    title: "Blue Lagoon Island",
    subtitle: "A full day of beach and island activities",
    category: "🚤 Tour",
    subcategory: "Island Excursion",
    destination: "Bahamas",
    location: "Near Paradise Island",
    imageUrl: "https://images.unsplash.com/photo-1540202404-a2f29016b523",
    gallery: [],
    rating: 4.7,
    reviewCount: 527,
    price: r"$$$",
    status: "TOURS TODAY",
    description:
        "A private island experience with beaches, water activities, food, and family-friendly areas.",
    whyYoullLoveIt:
        "It offers an easy way to enjoy a complete island day without planning every detail separately.",
    perfectFor: ["Families", "Couples", "Beach Day"],
    features: ["Guided Experience", "Family Friendly", "Ocean View"],
    pulse: "Afternoon departure has availability",
  ),

  Listing(
    id: "queen-staircase",
    title: "Queen's Staircase",
    subtitle: "Historic steps carved from limestone",
    category: "✨ Hidden Gem",
    subcategory: "Historic Site",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592",
    gallery: [],
    rating: 4.5,
    reviewCount: 365,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A historic limestone staircase surrounded by greenery and connected to Nassau's colonial history.",
    whyYoullLoveIt:
        "It is a quick but memorable stop that offers history, scenery, and great photos.",
    perfectFor: ["History", "Families", "Photography"],
    features: ["Hidden Gem", "Historic", "Photo Friendly"],
    pulse: null,
  ),

  Listing(
    id: "john-watlings-distillery",
    title: "John Watling's Distillery",
    subtitle: "Historic estate and local rum tasting",
    category: "🥃 Experience",
    subcategory: "Distillery",
    destination: "Bahamas",
    location: "Nassau",
    imageUrl: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f",
    gallery: [],
    rating: 4.6,
    reviewCount: 401,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A historic estate where visitors can explore Bahamian rum production and enjoy tastings.",
    whyYoullLoveIt:
        "It combines local history, beautiful grounds, and a relaxed tasting experience.",
    perfectFor: ["Couples", "Friends", "Local Culture"],
    features: ["Historic", "Guided Experience", "Local Favorite"],
    pulse: "Next tasting begins soon",
  ),

  Listing(
    id: "straw-market",
    title: "Nassau Straw Market",
    subtitle: "Local crafts, souvenirs, and handmade goods",
    category: "🛍 Shopping",
    subcategory: "Local Market",
    destination: "Bahamas",
    location: "Downtown Nassau",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9",
    gallery: [],
    rating: 4.2,
    reviewCount: 689,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A bustling downtown market with handmade crafts, souvenirs, clothing, and local vendors.",
    whyYoullLoveIt:
        "It is an easy place to browse local products and bring home something connected to the destination.",
    perfectFor: ["Shopping", "Families", "Local Culture"],
    features: ["Local Market", "Handmade", "Downtown"],
    pulse: "New vendors open today",
  ),

  Listing(
    id: "clifton-heritage-park",
    title: "Clifton Heritage Park",
    subtitle: "History, trails, beaches, and underwater art",
    category: "✨ Hidden Gem",
    subcategory: "Heritage Park",
    destination: "Bahamas",
    location: "West Nassau",
    imageUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
    gallery: [],
    rating: 4.7,
    reviewCount: 178,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A coastal heritage park offering trails, historic ruins, beaches, and cultural exhibits.",
    whyYoullLoveIt:
        "It combines nature, culture, and history in a quieter area away from central Nassau.",
    perfectFor: ["Families", "History", "Nature"],
    features: ["Hidden Gem", "Historic", "Ocean View", "Walking Trails"],
    pulse: null,
  ),

  Listing(
    id: "aura-nightclub",
    title: "Aura Nightclub",
    subtitle: "Late-night music and dancing",
    category: "🌙 Nightlife",
    subcategory: "Nightclub",
    destination: "Bahamas",
    location: "Paradise Island",
    imageUrl: "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2",
    gallery: [],
    rating: 4.3,
    reviewCount: 243,
    price: r"$$$",
    status: "TONIGHT",
    description:
        "A high-energy nightclub with DJs, dancing, premium drinks, and a stylish atmosphere.",
    whyYoullLoveIt:
        "It is a strong option for travellers looking for a lively late-night experience.",
    perfectFor: ["Friends", "Nightlife", "Dancing"],
    features: ["DJ", "Nightlife", "Dancing"],
    pulse: "DJ starts at 10 PM",
  ),
  Listing(
    id: "rome-colosseum-evening",
    title: "Colosseum at Golden Hour",
    subtitle: "Ancient Rome as the evening light settles in",
    category: "🏛 Landmark",
    subcategory: "Historic Landmark",
    destination: "Italy",
    location: "Historic Centre",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    gallery: [],
    rating: 4.9,
    reviewCount: 1842,
    price: r"$$",
    status: "OPEN TODAY",
    description:
        "Explore one of Rome's most recognizable landmarks during the softer evening light.",
    whyYoullLoveIt:
        "The history, scale, and atmosphere make it an unforgettable introduction to Rome.",
    perfectFor: ["History", "Couples", "Photography"],
    features: ["Historic", "Guided Experience", "Photo Friendly"],
    pulse: "Golden hour begins soon",
  ),

  Listing(
    id: "rome-trevi-fountain-night",
    title: "Trevi Fountain After Dark",
    subtitle: "See the fountain illuminated at night",
    category: "🏛 Landmark",
    subcategory: "Historic Landmark",
    destination: "Italy",
    location: "Historic Centre",
    imageUrl: "https://images.unsplash.com/photo-1529260830199-42c24126f198",
    gallery: [],
    rating: 4.8,
    reviewCount: 2315,
    price: r"$",
    status: "OPEN NOW",
    description:
        "Visit the Trevi Fountain after sunset when its lights create a completely different atmosphere.",
    whyYoullLoveIt:
        "It is especially memorable at night and fits naturally into an evening walk through central Rome.",
    perfectFor: ["Couples", "Night Walk", "Photography"],
    features: ["Historic", "Free", "Photo Friendly"],
    pulse: "Evening lights are on",
  ),

  Listing(
    id: "rome-trastevere-food-walk",
    title: "Trastevere Food Walk",
    subtitle: "Taste local favourites through cobblestone streets",
    category: "🚶 Tour",
    subcategory: "Food Tour",
    destination: "Italy",
    location: "Trastevere",
    imageUrl: "https://images.unsplash.com/photo-1531572753322-ad063cecc140",
    gallery: [],
    rating: 4.8,
    reviewCount: 624,
    price: r"$$$",
    status: "STARTS SOON",
    description:
        "A guided walk through Trastevere combining neighbourhood history with several local food stops.",
    whyYoullLoveIt:
        "You experience the neighbourhood through its streets, stories, and food instead of visiting one restaurant.",
    perfectFor: ["Food Lovers", "Couples", "Friends"],
    features: ["Guided Experience", "Local Favorite", "Walking Tour"],
    pulse: "Evening group leaves in 40 minutes",
  ),

  Listing(
    id: "rome-courtyard-pasta",
    title: "Courtyard Pasta Dinner",
    subtitle: "Fresh pasta in a quiet Roman courtyard",
    category: "🍝 Dining",
    subcategory: "Italian Restaurant",
    destination: "Italy",
    location: "Trastevere",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
    gallery: [],
    rating: 4.7,
    reviewCount: 418,
    price: r"$$$",
    status: "OPEN TONIGHT",
    description:
        "A relaxed dinner experience featuring fresh pasta, seasonal dishes, and a tucked-away courtyard.",
    whyYoullLoveIt:
        "It offers the slower, atmospheric dinner experience many travellers picture when imagining Rome.",
    perfectFor: ["Couples", "Date Night", "Food Lovers"],
    features: ["Outdoor Seating", "Romantic", "Local Favorite"],
    pulse: "A few courtyard tables remain",
  ),

  Listing(
    id: "rome-wine-cellar",
    title: "Historic Wine Cellar",
    subtitle: "Italian wine and small plates beneath old stone arches",
    category: "🍷 Bar",
    subcategory: "Wine Bar",
    destination: "Italy",
    location: "Historic Centre",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3",
    gallery: [],
    rating: 4.7,
    reviewCount: 289,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A cosy wine bar serving regional wines, cheeses, and small plates in a historic setting.",
    whyYoullLoveIt:
        "It is an easy stop before dinner or a relaxed way to finish an evening walk.",
    perfectFor: ["Couples", "Friends", "Date Night"],
    features: ["Wine", "Historic", "Small Plates"],
    pulse: "Wine tasting begins soon",
  ),

  Listing(
    id: "rome-orange-garden-sunset",
    title: "Orange Garden Sunset",
    subtitle: "A peaceful overlook above the rooftops of Rome",
    category: "🌅 Sunset",
    subcategory: "Scenic Viewpoint",
    destination: "Italy",
    location: "Aventine Hill",
    imageUrl: "https://images.unsplash.com/photo-1529154036614-a60975f5c760",
    gallery: [],
    rating: 4.8,
    reviewCount: 734,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A quiet garden and viewpoint offering broad views across Rome as the sun begins to set.",
    whyYoullLoveIt:
        "It gives you a calmer sunset experience away from the busiest central landmarks.",
    perfectFor: ["Couples", "Sunset", "Relaxing"],
    features: ["Hidden Gem", "Scenic View", "Free"],
    pulse: "Sunset begins in 45 minutes",
  ),
  Listing(
    id: "tokyo-sushi-counter",
    title: "Tsukiji Sushi Counter",
    subtitle: "Fresh sushi prepared directly in front of you",
    category: "🍣 Dining",
    subcategory: "Sushi",
    destination: "Japan",
    location: "Tsukiji",
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c",
    gallery: [],
    rating: 4.8,
    reviewCount: 912,
    price: r"$$$",
    status: "OPEN NOW",
    description:
        "An intimate counter-style sushi experience focused on fresh seafood and careful preparation.",
    whyYoullLoveIt:
        "Sitting at the counter lets you watch every piece being prepared and makes the meal feel personal.",
    perfectFor: ["Food Lovers", "Couples", "Solo Travelers"],
    features: ["Sushi", "Local Favorite", "Counter Seating"],
    pulse: "Shorter wait than usual",
  ),

  Listing(
    id: "tokyo-conveyor-sushi",
    title: "Shibuya Conveyor Sushi",
    subtitle: "A fun and casual introduction to Tokyo sushi",
    category: "🍣 Dining",
    subcategory: "Sushi",
    destination: "Japan",
    location: "Shibuya",
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754",
    gallery: [],
    rating: 4.5,
    reviewCount: 1340,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A lively conveyor-belt sushi restaurant with a broad selection and quick ordering.",
    whyYoullLoveIt:
        "It is approachable, fast, and easy to enjoy without planning a formal meal.",
    perfectFor: ["Friends", "Families", "Casual Meal"],
    features: ["Sushi", "Family Friendly", "Quick Stop"],
    pulse: "Tables are moving quickly",
  ),

  Listing(
    id: "tokyo-tonkotsu-ramen",
    title: "Late-Night Tonkotsu Ramen",
    subtitle: "Rich broth and noodles after a night in Shinjuku",
    category: "🍜 Dining",
    subcategory: "Ramen",
    destination: "Japan",
    location: "Shinjuku",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    gallery: [],
    rating: 4.8,
    reviewCount: 1684,
    price: r"$$",
    status: "OPEN LATE",
    description:
        "A compact ramen shop specializing in rich tonkotsu broth, customizable noodles, and late-night service.",
    whyYoullLoveIt:
        "It is warm, satisfying, and perfectly suited to the energy of Shinjuku after dark.",
    perfectFor: ["Food Lovers", "Nightlife", "Solo Travelers"],
    features: ["Ramen", "Open Late", "Local Favorite"],
    pulse: "Open late tonight",
  ),

  Listing(
    id: "tokyo-shoyu-ramen",
    title: "Asakusa Shoyu Ramen",
    subtitle: "A lighter soy-based bowl near the temple district",
    category: "🍜 Dining",
    subcategory: "Ramen",
    destination: "Japan",
    location: "Asakusa",
    imageUrl: "https://images.unsplash.com/photo-1591814468924-caf88d1232e1",
    gallery: [],
    rating: 4.7,
    reviewCount: 563,
    price: r"$$",
    status: "OPEN NOW",
    description:
        "A traditional shoyu ramen bowl served near Asakusa's historic streets and temples.",
    whyYoullLoveIt:
        "It pairs naturally with a day exploring Asakusa and offers a different style from heavier ramen.",
    perfectFor: ["Food Lovers", "Casual Lunch", "Solo Travelers"],
    features: ["Ramen", "Traditional", "Quick Stop"],
    pulse: "Lunch line is currently short",
  ),

  Listing(
    id: "tokyo-ueno-garden",
    title: "Ueno Park & Garden Walk",
    subtitle: "Museums, ponds, temples, and seasonal scenery",
    category: "🌸 Nature",
    subcategory: "Urban Park",
    destination: "Japan",
    location: "Ueno",
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951",
    gallery: [],
    rating: 4.7,
    reviewCount: 2104,
    price: r"$",
    status: "OPEN NOW",
    description:
        "A large urban park connecting gardens, cultural sites, museums, and peaceful walking routes.",
    whyYoullLoveIt:
        "It provides a slower, greener break from Tokyo's busiest districts.",
    perfectFor: ["Families", "Nature", "Photography"],
    features: ["Nature", "Walking Trails", "Family Friendly"],
    pulse: "Beautiful light this afternoon",
  ),

  Listing(
    id: "tokyo-akihabara-arcade",
    title: "Akihabara Arcade Night",
    subtitle: "Multi-floor games, lights, and Tokyo energy",
    category: "🎮 Entertainment",
    subcategory: "Arcade",
    destination: "Japan",
    location: "Akihabara",
    imageUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420",
    gallery: [],
    rating: 4.6,
    reviewCount: 1189,
    price: r"$$",
    status: "OPEN LATE",
    description:
        "A multi-level arcade packed with rhythm games, racing games, claw machines, and bright city energy.",
    whyYoullLoveIt:
        "It is easy to drop in for twenty minutes or stay for an entire evening.",
    perfectFor: ["Friends", "Gaming", "Night Out"],
    features: ["Entertainment", "Arcade", "Open Late"],
    pulse: "Tournament starting tonight",
  ),

  Listing(
    id: "tokyo-golden-gai",
    title: "Golden Gai After Dark",
    subtitle: "Tiny bars hidden along narrow Shinjuku lanes",
    category: "🌃 Nightlife",
    subcategory: "Bar District",
    destination: "Japan",
    location: "Shinjuku",
    imageUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390",
    gallery: [],
    rating: 4.6,
    reviewCount: 1475,
    price: r"$$$",
    status: "OPEN TONIGHT",
    description:
        "A maze of narrow lanes filled with compact bars, distinctive interiors, and late-night atmosphere.",
    whyYoullLoveIt:
        "Each tiny venue feels different, making the area ideal for spontaneous evening exploration.",
    perfectFor: ["Friends", "Nightlife", "Couples"],
    features: ["Nightlife", "Hidden Gem", "Open Late"],
    pulse: "The neighbourhood is coming alive",
  ),

  Listing(
    id: "tokyo-shibuya-sky",
    title: "Shibuya Sky at Sunset",
    subtitle: "A rooftop view above one of Tokyo's busiest districts",
    category: "🌃 Nightlife",
    subcategory: "Observation Deck",
    destination: "Japan",
    location: "Shibuya",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf",
    gallery: [],
    rating: 4.9,
    reviewCount: 1863,
    price: r"$$",
    status: "OPEN TODAY",
    description:
        "A high rooftop observation experience overlooking Shibuya and the wider Tokyo skyline.",
    whyYoullLoveIt:
        "Watching daylight turn into neon city lights creates one of Tokyo's strongest visual moments.",
    perfectFor: ["Couples", "Sunset", "Photography"],
    features: ["Scenic View", "Photo Friendly", "Nightlife"],
    pulse: "Sunset entry begins soon",
  ),
];
